apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sample-service-dev
namePrefix: dev-
commonLabels:
  env: dev
resources:
  - ../../base
  - namespace.yaml
images:
  - name: nginx
    newName: nginx
    newTag: "1.25-alpine"
patches:
  - target:
      kind: Deployment
      name: sample-service
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: sample-service
      spec:
        replicas: 1
        template:
          spec:
            containers:
              - name: sample-service
                env:
                  - name: APP_ENV
                    value: dev
