apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - external-secrets.yaml
  - monitoring.yaml
  - istio.yaml
  - external-secret-stores.yaml
  - trivy-operator.yaml
